os:
  - osx

osx_image: xcode9.4

language: python

python:
  - "2.7"
  - "3.7"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap bazelbuild/tap; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap-pin bazelbuild/tap; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bazel; fi

script:
  - bazel test ...
